# Generated by Django 2.0 on 2018-07-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vchr_name', models.CharField(max_length=100)),
                ('vchr_email', models.CharField(max_length=100)),
                ('txt_content', models.TextField()),
            ],
        ),
    ]
